#!/usr/bin/python

import flickrapi
import sys

'''Run this to authorize another program you've registered with Flickr.
The three arguments are:

1. The program's api key, which you get from Flickr.
2. The program's api secret, which you get from Flickr.
3. The program's permissions (read, write, or delete), which you determine.

After running, there will be an entry in your ~/.flickr directory with a token
that will allow the program to do what you authorized.'''

try:
    api_key = sys.argv[1]
    api_secret = sys.argv[2]
    permission = sys.argv[3]
except IndexError:
    sys.exit("Usage: %s <api_key> <api_secret> (read|write|delete)" % __file__)

flickr = flickrapi.FlickrAPI(api_key, api_secret)

# See https://github.com/sybrenstuvel/flickrapi/issues/69
flickr.authenticate_via_browser(perms=permission)
