#!/usr/bin/env python
# -*- encoding: utf-8

from flickrapi import FlickrAPI
import sys
import getopt

import json
import os
import webbrowser
from xml.etree import ElementTree as ET

usage = """Usage: up2flickr [options] [files]

Options:
  -p   make the photos public
  -h   show this help message

Upload image files to Flickr. The images will be private to
friends and family by default."""

# Flickr parameters
flickr_api_creds = json.load(open(
    os.path.join(os.environ["HOME"], ".flickr", "api_credentials.json")
))

user_id = flickr_api_creds["user_id"]
api_key = flickr_api_creds["api_key"]
api_secret = flickr_api_creds["api_secret"]

# Get the command line options.
try:
  options, filenames = getopt.getopt(sys.argv[1:], 'ph')
except getopt.GetoptError as err:
  print(str(err))
  sys.exit(2)

# Set the option values.
public = 0       # default
for o, a in options:``
  if o == '-p':
    public = 1
  else:
    print(usage)
    sys.exit()

# Upload the files on the command line.
flickr = FlickrAPI(api_key=api_key, secret=api_secret)

for fn in filenames:
    print("Uploading %s..." % fn)
    title = os.path.splitext(os.path.basename(fn))[0]
    response = flickr.upload(
        filename=fn,
        title=title,
        is_public=public,

        # Hide from public searches
        hidden=2,

        format='etree'
    )

    photo_id = response.find('photoid').text

    # Set the licence as CC-BY.
    resp = flickr.do_flickr_call(
        "flickr.photos.licenses.setLicense",
        photo_id=photo_id,
        license_id="4"
    )
    assert ET.tostring(resp) == b'<rsp stat="ok">\n</rsp>'

    photoURL = 'http://www.flickr.com/photos/%s@N03/%s/' % (user_id, photo_id)
    print("  %s" % photoURL)

webbrowser.open(photoURL)
