#!/usr/bin/env python
# -*- encoding: utf-8

from flickrapi import FlickrAPI
import sys
import getopt

import json
import os
import webbrowser
from xml.etree import ElementTree as ET

usage = """Usage: up2flickr [options] [files]

Options:
  -h   show this help message

Upload image files to Flickr."""


def flickr_dir(name):
    return os.path.join(os.environ["HOME"], ".flickr", name)


# Flickr parameters
flickr_api_creds = json.load(open(flickr_dir("api_credentials.json")))

user_id = flickr_api_creds["user_id"]
api_key = flickr_api_creds["api_key"]
api_secret = flickr_api_creds["api_secret"]

# Get the command line options.
try:
  options, filenames = getopt.getopt(sys.argv[1:], 'h')
except getopt.GetoptError as err:
  print(str(err))
  sys.exit(2)

# Upload the files on the command line.
flickr = FlickrAPI(api_key=api_key, secret=api_secret)

for fn in filenames:
    print("Uploading %s..." % fn)
    title = os.path.splitext(os.path.basename(fn))[0]
    photo_id = "44879366144"
    response = flickr.upload(
        filename=fn,
        title=title,

        # Make the image private
        is_public=0,

        # Hide from public searches
        hidden=2,

        format='etree'
    )

    photo_id = response.find('photoid').text

    # Set the licence as CC-BY.
    resp = flickr.do_flickr_call(
        "flickr.photos.licenses.setLicense",
        photo_id=photo_id,
        license_id="4"
    )
    assert ET.tostring(resp) == b'<rsp stat="ok">\n</rsp>'

    resp = flickr.do_flickr_call(
        "flickr.photos.getSizes",
        photo_id=photo_id
    )

    sizes = [
        dict(sz.items())
        for sz in resp.find("sizes").findall("size")
    ]

    out_path = os.path.join(
        os.environ["HOME"],
        "repos", "alexwlchan.net", "src", "_flickr", "photo_%s.json" % photo_id
    )

    with open(out_path, "w") as outfile:
        outfile.write(json.dumps(sizes))

    photoURL = 'http://www.flickr.com/photos/%s@N03/%s/' % (user_id, photo_id)
    print("  %s" % photoURL)

webbrowser.open(photoURL)
